global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "env"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: null
  routes:
    - receiver: slack
      matchers:
        - SLACK_WEBHOOK_URL=~".+"
    - receiver: sns
      matchers:
        - SNS_WEBHOOK_URL=~".+"

receivers:
  - name: slack
    webhook_configs:
      - url: ${SLACK_WEBHOOK_URL}
        send_resolved: true
  - name: sns
    webhook_configs:
      - url: ${SNS_WEBHOOK_URL}
        send_resolved: true
  - name: null

inhibit_rules:
  - source_matchers:
      - alertname="BackendDown"
    target_matchers:
      - alertname="AppDown"
    equal: ["env"]
