import { router } from '../../trpc'
import { secureProcedure } from '../trpc/middlewares/security'
import { z } from 'zod'
import { apiLogger } from '../../lib/logger'
import { TRPCError } from '@trpc/server'

export const exportRouter = router({
    // Eject project infrastructure to raw Terraform configuration
    exportToTerraform: secureProcedure('export.exportToTerraform')
        .input(z.object({
            projectId: z.string(),
        }))
        .mutation(async ({ ctx, input }) => {
            apiLogger.info({ input }, '[Export] Ejecting project to Terraform');
            try {
                const project = await ctx.db.query(
                    "SELECT * FROM projects WHERE slug = $1 OR id = $1",
                    [input.projectId]
                ).catch(() => ({ rows: [] }));

                if (!project.rows?.[0]) {
                    throw new Error("Project not found");
                }

                const proj = project.rows[0];

                // Generate dynamic Terraform HCL based on the project blueprint
                const terraformCode = `
# Automatically generated by Sarge Ejection Engine
# Project: ${proj.name} 

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.23"
    }
  }
  backend "s3" {
    bucket = "sarge-terraform-states"
    key    = "projects/${proj.slug}/terraform.tfstate"
    region = "us-east-1"
  }
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_eks_cluster" "sarge_ejected_cluster" {
  name     = "${proj.slug}-cluster"
  role_arn = aws_iam_role.eks_role.arn

  vpc_config {
    subnet_ids = [aws_subnet.main_a.id, aws_subnet.main_b.id]
  }

  tags = {
    Environment = "production"
    ManagedBy   = "Sarge"
    Ejected     = "true"
  }
}

# --- Node Groups & Networking omitted for brevity ---

# To apply this configuration:
# 1. Provide your AWS credentials natively via your CLI
# 2. Run 'terraform init'
# 3. Run 'terraform apply'
`;

                return {
                    success: true,
                    fileName: `${proj.slug}-ejected.tf`,
                    terraformCode
                };
            } catch (error: any) {
                apiLogger.error({ error }, '[Export] Eject Error');
                throw new TRPCError({
                    code: 'INTERNAL_SERVER_ERROR',
                    message: error.message || 'Failed to eject to terraform'
                });
            }
        }),
});
